### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by kurtheiligmann** [ericwlange/AndroidJSCore#31]
```
$ hemroid install javascriptcore
WARNING: make-standalone-toolchain.sh will be removed in r13. Please try make_standalone_toolchain.py now to make sure it works for your needs.
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
ERROR: Unknown option '--system'. See --help for usage.
Can't build toolchain for armeabi
```

I am trying to build to library to hopefully help in debugging a hang in the 2.2 pre release and the build steps don't work for me. Let me know what info is helpful or if there is anything I am missing.

**Comment by ericwlange** [comment]
Ack. It looks like the latest NDK has changed. If you roll back your NDK to
r10e it will work. I will take a look at getting the new NDK to build
properly.

**Comment by ericwlange** [comment]
Also ... please use the latest version 3.0-pre1 -- I have fixed the hanging bug

**Comment by kurtheiligmann** [comment]
I still get the hang in 3.0-pre1. I am calling a JS function multiple times (all on a single context) from Java as part of a test suite. I usually hangs between the 120-150th time through (a passing test will need to hit the function ~1200 times). A native debugger shows `Signal: SIGUSR2 (signal SIGUSR2)` in the console. I am glad to provide any information I can the will help.

**Comment by ericwlange** [comment]
Ha.  SIGUSR2 is a pretty useless signal.  It could mean anything.  Is there any message captured in Dalvik?  Remove the filter to "no filter" on messages and see if anything shows there.  Many times nothing shows with the app filter on.  Also do you have a stack dump for all the threads?  Where was the execution halted?

I will add a similar test to my suite and see if I can reproduce.  Can you give me a little more context on what the test does?  Does it call a single JS function multiple times or do you [create a new function (from Java) and call that new function (from Javascript)] multiple times?  If the latter, you could be running out of memory as functions will stick around until the context is garbage collected.  In the former case, that shouldn't be an issue.  Basically anything you can give me to help reproduce would be great.  I actually have nothing planned this weekend, so I can spend some time on it. :)

**Comment by kurtheiligmann** [comment]
The JS is a logic engine that is admittedly very "statey". Its proprietary so its hard to share. It manages a number of lists and moving objects through the lists. I will try to see if I can get it into a state that my employer will let me share.

I tried both creating a new `Function` each time and reusing a single instance with no major difference. It may well be a memory issue, but my profiling so far doesn't show a huge memory footprint. 

Thanks again for the attention to this.

**Comment by kurtheiligmann** [comment]
I sent you an invite to a private repo with code to reproduce the hanging issue.

**Comment by ericwlange** [comment]
I am able to reproduce the issue.  There are two bugs:

1) In some cases when the Java garbage collector attempts to `unprotect` a JS value, it crashes because the JS garbage collector already collected it.  This is just a mismatched `protect`/`unprotect` somewhere.  I was able to workaround it by removing the `unprotect` call, but that is just a hack.  I will track down the mismatch.

2) The same hanging bug that I thought I fixed in 2.2+ still exists, only it now only shows up under extreme conditions (I have no clue what your code is trying to do, but it sure does exercise the system!).  I was able to work around it by running the test in the same background thread that all JS code runs in.  It is an unexposed method that is accessible through reflections.

The result of these two workarounds is that both tests succeed.  Well, `TestTerminationTrue` runs to completion and succeeds anyway.  `TestTerminationFalse` runs without end, showing a progress of 0.02.  I let it run to over 150k iterations and it showed no sign of stopping, so I assume, as the name suggests, it isn't supposed to terminate.

If you can confirm this is the correct behavior, I will go about fixing these two bugs.  I really don't know what is causing (2).  I can think of two workarounds that will solve the problem, but I would really like to understand root cause.  What is happening is this:

There is a single background thread that executes code in a synchronous queue.  This serves two purposes: (1) it ensures that no JS code is executed in the main thread.  On older versions of Android, the main thread stack is so shallow that running some JS operations will cause a stack overflow.  But other pthreads have a 1MB stack, so this doesn't occur.  (2) it forces thread safety, as JS is intended to be a single-threaded VM.  Otherwise, calling the same `JSContext` from multiple threads simultaneously could clobber state irreparably.

The code to ensure it is in [`JSWorkerQueue.java`](https://github.com/ericwlange/AndroidJSCore/blob/master/AndroidJSCore/AndroidJSCore/src/main/java/org/liquidplayer/webkit/javascriptcore/JSWorkerQueue.java).  I originally had this implementation on the C++ side using `pthread` directly, but the hanging bug was more pronounced.  When I moved it to the Java side, it seemed to go away (until now).  I have tried implementing this logic in at least 6 different ways, all with the same outcome.  My current version since yesterday uses `Semaphore` and an explicit loop.  Exact same story at exactly the same (approximate) spot.  What happens is that a thread will block on the semaphore waiting for execution to finish in the JavaScript looper.  That execution will finish and the semaphore will be released (I can put messages on both sides of `release` and see them both).  But for some maddening reason, the blocking thread will not get the notification that the semaphore has been released and will deadlock indefinitely.  I cannot figure out why and no Google search is turning up hints.  The best I can guess is that some asynchronous event, like garbage collection (on either the Java or JavaScript end), is occurring at approximately the same time during execution and causing the notification to get lost, but I can't seem to validate that theory or even speculate as to why it would have that effect.

One solution that I am fairly sure will work is to launch an `AsyncTask` from a pool of one and utilize that.  I will test that now.  But unfortunately that doesn't explain why the other method doesn't work and makes me worry that it just buries the issue deeper.  But let me try it.

Will keep you posted.

**Comment by ericwlange** [comment]
Ok, I believe I have fixed the problem.

Please see the version of `AndroidJSCore-3.0-pre2` that I pushed to your private repo.

The issue, I learned, is that it is not necessary for me to ensure thread safety because JavaScriptCore already does it.  It has a mutex lock that it uses.  Because I was also using my own mutex, it would get into a state where each one was deadlocking on the other.  So I removed my single-threaded code and instead only ensure that it doesn't run on the main thread.  The hanging problem goes away.

I also fixed the protect/unprotect imbalance.

I let `TestTerminationFalse` run as long as it could.  It got to about 871k updates before it ran out of memory.  I am not quite sure why it runs out of memory, though I have an idea.  I will try to track that down.

In the meantime, please verify that this fixes the hanging bug and I will check it in and roll a new release.

**Comment by ericwlange** [comment]
Ok, memory leak fixed.  Please validate.

**Comment by kurtheiligmann** [comment]
Wow. Thanks for putting so much into this. 

`TestTerminationFalse` isn't actually supposed to run in perpetuity. It may be a bug introduced by my efforts to get the code into a sharable state. I would be willing to be that issue is on our side. Even when is does work correctly, we should have far fewer than 871k updates. 

I was able to validate that `TestTerminationTrue` ran to completion.

**Comment by ericwlange** [comment]
Glad to help.  Thanks for sending me a detailed and complete test case.  It has been hard to swat this bug, because it only shows up under extreme circumstances and I haven't been using it to that extent in my projects.  I will push 3.0-pre2 to releases now.

**Comment by ericwlange** [comment]
This is now fixed in 3.0-pre2

**Comment by kurtheiligmann** [comment]
I was also able to verify that TestTerminationFalse never reached completion because of a bug in the JavaScript. All is good!
